python: can't open file '/data/project/alessiobot/add_orfana_pd-italia.py': [Errno 2] No such file or directory
python: can't open file '/data/project/alessiobot/add_orfana_pd-italia.py': [Errno 2] No such file or directory
python: can't open file '/data/project/alessiobot/add_orfana_pd-italia.py': [Errno 2] No such file or directory
Run time:  0.08
Run time:  0.11
Traceback (most recent call last):
  File "/data/project/alessiobot/script/immagini/img_orfana_PD_italia.py", line 53, in <module>
    main()
  File "/data/project/alessiobot/script/immagini/img_orfana_PD_italia.py", line 22, in main
    for page in add_lists:
  File "/shared/pywikipedia/core/pywikibot/pagegenerators.py", line 787, in TextfilePageGenerator
    f = codecs.open(filename, 'r', config.textfile_encoding)
  File "/usr/lib/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'data/immagini_PD-italia/20141008.txt'
CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
<type 'exceptions.IOError'>
Run time:  0.08
Traceback (most recent call last):
  File "/data/project/alessiobot/script/immagini/img_orfana_PD_italia.py", line 53, in <module>
    main()
  File "/data/project/alessiobot/script/immagini/img_orfana_PD_italia.py", line 22, in main
    for page in add_lists:
  File "/shared/pywikipedia/core/pywikibot/pagegenerators.py", line 787, in TextfilePageGenerator
    f = codecs.open(filename, 'r', config.textfile_encoding)
  File "/usr/lib/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '../../data/immagini/immagini_PD-italia/20141008.txt'
CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
<type 'exceptions.IOError'>
